BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "matches" (
	"matchID"	int,
	"Team1"	char,
	"Team2"	char,
	"location"	char,
	"date"	date,
	"stadium"	char,
	"price_range"	char,
	"time1"	time,
	"desc"	char,
	"day"	char,
	"match_type"	char
);
CREATE TABLE IF NOT EXISTS "users" (
	"userID"	char,
	"email"	char,
	"username"	char,
	"password_hash"	char,
	"salt"	char,
	PRIMARY KEY("userID")
);
CREATE TABLE IF NOT EXISTS "orders" (
	"userID"	char,
	"orderID"	char,
	"email"	char,
	"matchID"	int,
	"seat_num"	char,
	"food_n_drinks"	bool,
	"transport"	bool,
	PRIMARY KEY("userID")
);
INSERT INTO "matches" ("matchID","Team1","Team2","location","date","stadium","price_range","time1","desc","day","match_type") VALUES (357576,'Gujarat Titans','Chennai Super Kings','Ahmedabad','2023-03-31','Narendra Modi Stadium','790 - 14200','19:30:00','In the upcoming match, the Gujarat Titans will have faced the Chennai Super Kings. This clash won''t just have been a cricket match; it will have mirrored life''s uncertainties. The boundaries they will have breached and the wickets they will have defended will have symbolized the challenges we face daily. In this arena, it won''t just have been about the game but the resilience to tackle the unexpected, much like life''s unpredictability. Both teams will have stood as a testament to determination, and every delivery and stroke will have been a chapter in the novel of existence.','Fri','League'),
 (167746,'Punjab Kings','Kolkata Knight Riders','Mohali','2023-04-01','PCA IS Bindra Stadium','760 - 14400','15:30:00','In the forthcoming contest, Punjab Kings will have gone head-to-head with the Kolkata Knight Riders. This clash won''t merely be a cricket match; it will have embodied the spirit of competition and camaraderie. Each delivery sent down and every stroke played will have contributed to the narrative of a fascinating cricketing story. The dynamics of the game will have been a reflection of the ebb and flow of life, and in this encounter, it won''t just have been about sportsmanship, but a celebration of the human spirit''s unwavering determination.','Sat','League'),
 (152199,'Lucknow Super Giants','Delhi Captials','Lucknow','2023-04-01','Ekana Cricket Stadium','670 - 11700','19:30:00','In the upcoming match, the Lucknow Super Giants will have challenged the Delhi Capitals. This encounter won''t be just a cricket game; it will have been a captivating chapter in the story of determination and sportsmanship. The players'' skill and strategy on the field will have reflected life''s unpredictability and the need to adapt to changing circumstances. Every boundary scored and every wicket taken will have added to the tale of this match, celebrating the spirit of cricket and the resilience of the human spirit.','Sat','League'),
 (598210,'Sunrisers Hyderabad','Rajasthan Royals','Hyderabad','2023-04-02','Rajiv Gandhi International Stadium','750 - 10900','15:30:00','In the imminent face-off, Sunrisers Hyderabad will have taken on the Rajasthan Royals. This contest won''t be merely a cricket match; it will have been a captivating portrayal of the ever-changing tides of competition and life itself. Each delivery bowled and every boundary struck will have been part of the narrative, embodying the philosophy that every moment in the game, as in life, is an opportunity for growth and triumph. This match will have been a testament to the enduring spirit of the players and the lessons cricket imparts.','Sun','League'),
 (289765,'Royal Challengers Bangalore','Mumbai Indians','Bengaluru','2023-04-02','M. Chinnaswamy Stadium','860 - 11600','19:30:00','In the forthcoming encounter, the Royal Challengers Bangalore will have faced the Mumbai Indians. This contest won''t have been just a cricket match; it will have symbolized the pinnacle of sportsmanship and skill. Each delivery bowled and every boundary struck will have contributed to the unfolding drama, akin to life''s unpredictable turns. It will have been a celebration of the unwavering dedication of the players and the enduring spirit of cricket, reminding us that challenges are opportunities in disguise.','Sun','League'),
 (335320,'Chennai Super Kings','Lucknow Super Giants','Chennai','2023-04-03','M.A Chidambaram Stadium','940 - 10600','19:30:00','In the impending showdown, the Chennai Super Kings will have taken on the Lucknow Super Giants. This match won''t merely have been a cricket game; it will have embodied the essence of competition and perseverance. Every ball bowled and every run scored will have woven into a narrative mirroring life''s twists and turns. The spirit and determination of the players on both sides will have showcased the core philosophy of cricket, where challenges are embraced as opportunities for growth and victory.','Mon','League'),
 (289951,'Delhi Capitals','Gujarat Titans','Delhi','2023-04-04','Arun Jaitley Stadium','750 - 12100','19:30:00','In the forthcoming clash, the Delhi Capitals will have challenged the Gujarat Titans. This match won''t have been just a cricket game; it will have encapsulated the spirit of sportsmanship and strategic play. Each delivery bowled and every run scored will have contributed to the unfolding drama, mirroring life''s intricate tapestry. The players'' determination and resilience will have exemplified the profound philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Tue','League'),
 (829122,'Rajasthan Royals','Punjab Kings','Guwahati','2023-04-05','Barsapara Stadium','770 - 10700','19:30:00','In the upcoming duel, the Rajasthan Royals will have faced the Punjab Kings. This contest won''t have been merely a cricket match; it will have embodied the essence of competition and camaraderie. Every delivery bowled and every boundary struck will have been a part of the ongoing narrative, mirroring life''s ever-changing dynamics. The players'' dedication and fighting spirit will have exemplified the enduring philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Wed','League'),
 (354499,'Kolkata Knight Riders','Royal Challengers Bangalore','Kolkata ','2023-04-06','Rajiv Gandhi International Stadium','1000 - 13600','19:30:00','In the forthcoming encounter, the Kolkata Knight Riders will have taken on Royal Challengers Bangalore. This contest won''t have been just a cricket match; it will have symbolized the zenith of sportsmanship and skill. Each delivery bowled and every boundary struck will have woven into the ongoing drama, mirroring the intricate tapestry of life. It will have been a celebration of the players'' unwavering dedication and the profound philosophy of cricket, reminding us that challenges are stepping stones to success.','Thu','League'),
 (707775,'Lucknow Super Giants','Sunrisers Hyderabad','Lucknow','2023-04-07','Ekana Cricket Stadium','790 - 14000','19:30:00','In the upcoming battle, the Lucknow Super Giants will have gone head-to-head with Sunrisers Hyderabad. This match won''t have been merely a cricket game; it will have encapsulated the essence of competition and perseverance. Every ball bowled and every run scored will have woven into the unfolding narrative, mirroring life''s twists and turns. The spirit and determination of the players on both sides will have showcased the core philosophy of cricket, where challenges are embraced as opportunities for growth and victory.','Fri','League'),
 (396950,'Rajasthan Royals','Delhi Captials','Guwahati','2023-04-08','Barsapara Stadium','970 - 12800','15:30:00','In the impending face-off, the Rajasthan Royals will have taken on the Delhi Capitals. This contest won''t have been merely a cricket match; it will have embodied the spirit of competition and camaraderie. Each delivery bowled and every run scored will have been part of the unfolding narrative, mirroring life''s ever-changing dynamics. The players'' dedication and fighting spirit will have exemplified the enduring philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Sat','League'),
 (380664,'Mumbai Indians','Chennai Super Kings','Mumbai','2023-04-08','Wankhede Stadium','720 - 12800','19:30:00','In the upcoming epic showdown, the Mumbai Indians will have faced the Chennai Super Kings. This match won''t have been just a cricket game; it will have symbolized the pinnacle of sportsmanship and skill. Each delivery bowled and every boundary struck will have contributed to the ongoing drama, akin to life''s unpredictable twists and turns. It will have been a celebration of the unwavering dedication of the players and the enduring spirit of cricket, reminding us that challenges are opportunities in disguise.','Sat','League'),
 (849381,'Gujarat Titans','Kolkata Knight Riders','Ahmedabad','2023-04-09','Narendra Modi Stadium','690 - 11500','15:30:00','In the imminent clash, the Gujarat Titans will have gone head-to-head with the Kolkata Knight Riders. This contest won''t have been merely a cricket match; it will have embodied the spirit of competition and perseverance. Every ball bowled and every run scored will have woven into the unfolding narrative, mirroring life''s twists and turns. The spirit and determination of the players on both sides will have showcased the core philosophy of cricket, where challenges are embraced as opportunities for growth and victory.','Sun','League'),
 (216069,'Sunrisers Hyderabad','Punjab Kings','Hyderabad','2023-04-09','Rajiv Gandhi International Stadium','810 - 13500','19:30:00','In the upcoming duel, Sunrisers Hyderabad will have taken on the Punjab Kings. This match won''t have been merely a cricket game; it will have encapsulated the essence of competition and sportsmanship. Every delivery bowled and every run scored will have contributed to the ongoing narrative, mirroring life''s intricate tapestry. The players'' dedication and fighting spirit will have exemplified the profound philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Sun','League'),
 (307796,'Royal Challengers Bangalore','Lucknow Super Giants','Bengaluru','2023-04-10','M. Chinnaswamy Stadium','860 - 12700','19:30:00','In the impending battle, Royal Challengers Bangalore will have challenged the Lucknow Super Giants. This match won''t have been just a cricket game; it will have embodied the essence of competition and perseverance. Every delivery bowled and every run scored will have woven into the unfolding narrative, mirroring life''s twists and turns. The spirit and determination of the players on both sides will have showcased the core philosophy of cricket, where challenges are embraced as opportunities for growth and victory.','Mon','League'),
 (128717,'Delhi Capitals','Mumbai Indians','Delhi','2023-04-11','Arun Jaitley Stadium','940 - 10500','19:30:00','In the upcoming epic showdown, the Delhi Capitals will have taken on the Mumbai Indians. This match won''t have been merely a cricket game; it will have symbolized the pinnacle of sportsmanship and skill. Each delivery bowled and every boundary struck will have contributed to the ongoing drama, akin to life''s unpredictable twists and turns. It will have been a celebration of the unwavering dedication of the players and the enduring spirit of cricket, reminding us that challenges are opportunities in disguise.','Tue','League'),
 (146740,'Chennai Super Kings','Rajasthan Royals','Chennai','2023-04-12','M.A Chidambaram Stadium','810 - 11900','19:30:00','In the forthcoming contest, the Chennai Super Kings will have faced the Rajasthan Royals. This match won''t have been just a cricket game; it will have embodied the spirit of competition and camaraderie. Each delivery bowled and every run scored will have been part of the ongoing narrative, mirroring life''s ever-changing dynamics. The players'' dedication and fighting spirit will have exemplified the enduring philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Wed','League'),
 (585027,'Punjab Kings','Gujarat Titans','Mohali','2023-04-13','PCA IS Bindra Stadium','750 - 12400','19:30:00','In the upcoming duel, the Punjab Kings will have taken on the Gujarat Titans. This match won''t have been merely a cricket game; it will have encapsulated the essence of competition and sportsmanship. Every delivery bowled and every run scored will have contributed to the ongoing narrative, mirroring life''s intricate tapestry. The players'' dedication and fighting spirit will have exemplified the profound philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Thu','League'),
 (285468,'Kolkata Knight Riders','Sunrisers Hyderabad','Kolkata ','2023-04-14','Eden Gardens Stadium','1200-10000','19:30:00','In the impending clash, the Kolkata Knight Riders will have gone head-to-head with Sunrisers Hyderabad. This contest won''t have been merely a cricket match; it will have embodied the spirit of competition and camaraderie. Every ball bowled and every run scored will have been part of the unfolding narrative, mirroring life''s ever-changing dynamics. The players'' dedication and fighting spirit will have showcased the enduring philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Fri','League'),
 (894337,'Royal Challengers Bangalore','Delhi Captials','Bengaluru','2023-04-15','M. Chinnaswamy Stadium','700 - 10900','15:30:00','In the forthcoming face-off, Royal Challengers Bangalore will have faced the Delhi Capitals. This contest won''t have been merely a cricket match; it will have embodied the essence of competition and sportsmanship. Every delivery bowled and every run scored will have contributed to the ongoing narrative, mirroring life''s intricate tapestry. The players'' dedication and fighting spirit will have exemplified the profound philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Sat','League'),
 (545223,'Lucknow Super Giants','Punjab Kings','Lucknow','2023-04-15','Ekana Cricket Stadium','940 - 12800','19:30:00','In the thrilling encounter, the Lucknow Super Giants will have taken on the Punjab Kings. This match won''t have been merely a cricket game; it will have embodied the essence of competition and sportsmanship. Every delivery bowled and every run scored will have contributed to the ongoing narrative, mirroring life''s intricate tapestry. The players'' dedication and fighting spirit will have exemplified the profound philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Sat','League'),
 (317226,'Mumbai Indians','Kolkata Knight Riders','Mumbai','2023-04-16','Wankhede Stadium','800 - 13900','15:30:00','The Mumbai Indians will have faced the Kolkata Knight Riders in a high-voltage clash, featuring a display of explosive batting and clever seam bowling. This match won''t have been just a cricket game; it will have symbolized the zenith of sportsmanship and skill. Each delivery bowled and every boundary struck will have contributed to the ongoing drama, akin to life''s unpredictable twists and turns. It will have been a celebration of the unwavering dedication of the players and the enduring spirit of cricket, reminding us that challenges are opportunities in disguise.','Sun','League'),
 (461942,'Gujarat Titans','Rajasthan Royals','Ahmedabad','2023-04-16','Narendra Modi Stadium','760 - 13500','19:30:00','In the anticipated showdown, the Gujarat Titans will have gone head-to-head with the Rajasthan Royals. This contest won''t have been merely a cricket match; it will have embodied the spirit of competition and perseverance. Every ball bowled and every run scored will have woven into the unfolding narrative, mirroring life''s twists and turns. The spirit and determination of the players on both sides will have showcased the core philosophy of cricket, where challenges are embraced as opportunities for growth and victory.','Sun','League'),
 (454362,'Royal Challengers Bangalore','Chennai Super Kings','Bengaluru','2023-04-17','M. Chinnaswamy Stadium','660 - 13700','19:30:00','Royal Challengers Bangalore will have faced the Chennai Super Kings in a high-stakes battle, promising an exciting clash of power-hitting and strategic bowling. This contest won''t have been just a cricket match; it will have mirrored life''s uncertainties. The boundaries they breach and the wickets they defend will have symbolized the challenges we face daily. In this arena, it won''t have been just about the game but the resilience to tackle the unexpected, much like life''s unpredictability. Both teams will have stood as a testament to determination, and every delivery and stroke will have been a chapter in the novel of existence.','Mon','League'),
 (143078,'Sunrisers Hyderabad','Mumbai Indians','Hyderabad','2023-04-18','Rajiv Gandhi International Stadium','790 - 15000','19:30:00','Sunrisers Hyderabad will have gone head-to-head with the Mumbai Indians in a thrilling match characterized by thrilling catches and powerful sixes, with both teams showing their mettle. This encounter won''t have been just a cricket game; it will have embodied the spirit of competition and camaraderie. Each delivery bowled and every run scored will have been part of the unfolding narrative, mirroring life''s ever-changing dynamics. The players'' dedication and fighting spirit will have exemplified the enduring philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Tue','League'),
 (280014,'Rajasthan Royals','Lucknow Super Giants','Jaipur','2023-04-19','Sawai Mansingh Stadium','730 - 14200','19:30:00','Rajasthan Royals will have faced the Lucknow Super Giants in an intense battle of skills and strategy. This match won''t have been just a cricket game; it will have encapsulated the spirit of competition and camaraderie. Each delivery bowled and every run scored will have been part of the unfolding narrative, mirroring life''s ever-changing dynamics. The players'' dedication and fighting spirit will have exemplified the enduring philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Wed','League'),
 (638738,'Punjab Kings','Royal Challengers Bangalore','Mohali','2023-04-20','PCA IS Bindra Stadium','740 - 12400','15:30:00','Punjab Kings will have gone head-to-head with Royal Challengers Bangalore, promising an exciting clash of power-hitting and strategic bowling. This contest won''t have been just a cricket match; it will have mirrored life''s uncertainties. The boundaries they breach and the wickets they defend will have symbolized the challenges we face daily. In this arena, it won''t have been just about the game but the resilience to tackle the unexpected, much like life''s unpredictability. Both teams will have stood as a testament to determination, and every delivery and stroke will have been a chapter in the novel of existence.','Thu','League'),
 (367625,'Delhi Capitals','Kolkata Knight Riders','Delhi','2023-04-20','Arun Jaitley Stadium','660 - 11700','19:30:00','Delhi Capitals will have challenged the Kolkata Knight Riders in an epic showdown, featuring a combination of explosive batting and clever seam bowling. This match won''t have been merely a cricket game; it will have embodied the essence of competition and sportsmanship. Every delivery bowled and every run scored will have contributed to the ongoing narrative, mirroring life''s intricate tapestry. The players'' dedication and fighting spirit will have exemplified the profound philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Thu','League'),
 (247587,'Chennai Super Kings','Sunrisers Hyderabad','Chennai','2023-04-21','M.A Chidambaram Stadium','950 - 11100','19:30:00','Chennai Super Kings will have taken on Sunrisers Hyderabad in a thrilling encounter, characterized by thrilling catches and powerful sixes. This match won''t have been just a cricket game; it will have embodied the spirit of competition and perseverance. Every ball bowled and every run scored will have woven into the unfolding narrative, mirroring life''s twists and turns. The spirit and determination of the players on both sides will have showcased the core philosophy of cricket, where challenges are embraced as opportunities for growth and victory.','Fri','League'),
 (658531,'Lucknow Super Giants','Gujarat Titans','Lucknow','2023-04-22','Ekana Cricket Stadium','970 - 13300','15:30:00','The Lucknow Super Giants will have faced the Gujarat Titans in a contest that won''t have been merely a cricket match; it will have embodied the spirit of competition and camaraderie. Every delivery bowled and every run scored will have been part of the unfolding narrative, mirroring life''s ever-changing dynamics. The players'' dedication and fighting spirit will have exemplified the enduring philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Sat','League'),
 (299078,'Mumbai Indians','Punjab Kings','Mumbai','2023-04-22','Wankhede Stadium','870 - 12300','19:30:00','The Mumbai Indians will have faced the Punjab Kings in a high-voltage clash, featuring a display of explosive batting and clever seam bowling. This match won''t have been just a cricket game; it will have symbolized the zenith of sportsmanship and skill. Each delivery bowled and every boundary struck will have contributed to the ongoing drama, akin to life''s unpredictable twists and turns. It will have been a celebration of the unwavering dedication of the players and the enduring spirit of cricket, reminding us that challenges are opportunities in disguise.','Sat','League'),
 (861529,'Royal Challengers Bangalore','Rajasthan Royals','Bengaluru','2023-04-23','M. Chinnaswamy Stadium','800 - 14900','15:30:00','Royal Challengers Bangalore will have taken on the Rajasthan Royals in an epic encounter, promising an exciting clash of power-hitting and strategic bowling. This match won''t have been merely a cricket game; it will have embodied the essence of competition and sportsmanship. Every delivery bowled and every run scored will have contributed to the ongoing narrative, mirroring life''s intricate tapestry. The players'' dedication and fighting spirit will have exemplified the profound philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Sun','League'),
 (343540,'Kolkata Knight Riders','Chennai Super Kings','Kolkata ','2023-04-23','Eden Gardens Stadium','1200-10000','19:30:00','The Kolkata Knight Riders will have faced the Chennai Super Kings in an intense battle of skills and strategy. This contest won''t have been merely a cricket match; it will have embodied the spirit of competition and perseverance. Every ball bowled and every run scored will have woven into the unfolding narrative, mirroring life''s twists and turns. The spirit and determination of the players on both sides will have showcased the core philosophy of cricket, where challenges are embraced as opportunities for growth and victory.','Sun','League'),
 (510425,'Sunrisers Hyderabad','Delhi Captials','Hyderabad','2023-04-24','Rajiv Gandhi International Stadium','700 - 11700','19:30:00','Sunrisers Hyderabad will have challenged the Delhi Capitals in a thrilling match characterized by thrilling catches and powerful sixes. This match won''t have been just a cricket game; it will have mirrored life''s uncertainties. The boundaries they breach and the wickets they defend will have symbolized the challenges we face daily. In this arena, it won''t have been just about the game but the resilience to tackle the unexpected, much like life''s unpredictability. Both teams will have stood as a testament to determination, and every delivery and stroke will have been a chapter in the novel of existence.','Mon','League'),
 (741001,'Gujarat Titans','Mumbai Indians','Ahmedabad','2023-04-25','Narendra Modi Stadium','760 - 12800','19:30:00','The Gujarat Titans will have gone head-to-head with the Mumbai Indians in an exciting contest that won''t have been merely a cricket match; it will have embodied the spirit of competition and camaraderie. Every delivery bowled and every run scored will have been part of the unfolding narrative, mirroring life''s ever-changing dynamics. The players'' dedication and fighting spirit will have exemplified the enduring philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Tue','League'),
 (803406,'Royal Challengers Bangalore','Kolkata Knight Riders','Bengaluru','2023-04-26','M. Chinnaswamy Stadium','930 - 12800','19:30:00','Royal Challengers Bangalore will have taken on the Kolkata Knight Riders in a high-stakes battle, promising an exciting clash of power-hitting and strategic bowling. This contest won''t have been just a cricket match; it will have mirrored life''s uncertainties. The boundaries they breach and the wickets they defend will have symbolized the challenges we face daily. In this arena, it won''t have been just about the game but the resilience to tackle the unexpected, much like life''s unpredictability. Both teams will have stood as a testament to determination, and every delivery and stroke will have been a chapter in the novel of existence.','Wed','League'),
 (780844,'Rajasthan Royals','Chennai Super Kings','Jaipur','2023-04-27','Sawai Mansingh Stadium','870 - 14200','19:30:00','Rajasthan Royals will have faced the Chennai Super Kings in an intense battle of skills and strategy. This match won''t have been merely a cricket game; it will have embodied the spirit of competition and perseverance. Every ball bowled and every run scored will have woven into the unfolding narrative, mirroring life''s twists and turns. The spirit and determination of the players on both sides will have showcased the core philosophy of cricket, where challenges are embraced as opportunities for growth and victory.','Thu','League'),
 (121113,'Punjab Kings','Lucknow Super Giants','Mohali','2023-04-28','PCA IS Bindra Stadium','890 - 13500','19:30:00','Punjab Kings will have gone head-to-head with the Lucknow Super Giants in a contest that won''t have been merely a cricket match; it will have embodied the spirit of competition and camaraderie. Every delivery bowled and every run scored will have been part of the unfolding narrative, mirroring life''s ever-changing dynamics. The players'' dedication and fighting spirit will have exemplified the enduring philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Fri','League'),
 (656652,'Kolkata Knight Riders','Gujarat Titans','Kolkata ','2023-04-29','Eden Gardens Stadium','1200-10000','15:30:00','The Kolkata Knight Riders will have faced the Gujarat Titans in an exciting contest that won''t have been just a cricket game; it will have symbolized the zenith of sportsmanship and skill. Each delivery bowled and every boundary struck will have contributed to the ongoing drama, akin to life''s unpredictable twists and turns. It will have been a celebration of the unwavering dedication of the players and the enduring spirit of cricket, reminding us that challenges are opportunities in disguise.','Sat','League'),
 (283850,'Delhi Capitals','Sunrisers Hyderabad','Delhi','2023-04-29','Arun Jaitley Stadium','950 - 13900','19:30:00','Delhi Capitals will have challenged Sunrisers Hyderabad in a thrilling match characterized by thrilling catches and powerful sixes, with both teams showing their mettle. This match won''t have been merely a cricket game; it will have embodied the essence of competition and sportsmanship. Every delivery bowled and every run scored will have contributed to the ongoing narrative, mirroring life''s intricate tapestry. The players'' dedication and fighting spirit will have exemplified the profound philosophy of cricket, where each challenge is an opportunity for personal and collective growth.','Sat','League'),
 (648755,'Chennai Super Kings','Punjab Kings','Chennai','2023-04-30','M.A Chidambaram Stadium','770 - 12900','15:30:00','Chennai Super Kings will have taken on Punjab Kings in a high-voltage clash, featuring a display of explosive batting and clever seam bowling. This match won''t have been just a cricket game; it will have mirrored life''s uncertainties. The boundaries they breach and the wickets they defend will have symbolized the challenges we face daily. In this arena, it won''t have been just about the game but the resilience to tackle the unexpected, much like life''s unpredictability. Both teams will have stood as a testament to determination, and every delivery and stroke will have been a chapter in the novel of existence.','Sun','League'),
 (699860,'Mumbai Indians','Rajasthan Royals','Mumbai','2023-04-30','Wankhede Stadium','770 - 13900','19:30:00','In the vast arena of the Indian Premier League, the Mumbai Indians and the Rajasthan Royals stand as metaphorical rivals. Mumbai, a city perpetually in motion, champions a legacy of stardom and victory. Meanwhile, Rajasthan, steeped in its regal past, cherishes the spirit of the underdog, nurturing blossoming talents like a garden of hope. When they cross paths, it''s more than a cricket match; it''s a clash of narratives, the metropolis versus the monarchy.','Sun','League'),
 (513138,'Lucknow Super Giants','Royal Challengers Bangalore','Lucknow','2023-05-01','Ekana Cricket Stadium','670 - 11800','19:30:00','In the tapestry of the IPL, the Lucknow Super Giants are the newest thread, eagerly weaving their tale of ambition into the cricketing fabric. Facing them is the perennial favorite, Royal Challengers Bangalore, a team with its own well-worn narrative, a tale of stars and fans. This encounter is a duel of dreams - the ambition of Lucknow against the legacy of Bangalore.','Mon','League'),
 (295652,'Gujarat Titans','Delhi Captials','Ahmedabad','2023-05-02','Narendra Modi Stadium','920 - 11900','19:30:00','Two franchises, the Gujarat Titans and the Delhi Capitals, each carrying the essence of their regions. The Titans, like the resilient people of Gujarat, possess strength and determination, striving for glory. Delhi Capitals, the embodiment of a nation''s capital, symbolize consistency and strategy. Their encounter is not just a match; it''s a reflection of the ethos of two diverse yet connected parts of India.','Tue','League'),
 (721208,'Lucknow Super Giants','Chennai Super Kings','Lucknow','2023-05-03','Ekana Cricket Stadium','970 - 11600','15:30:00','In this unfolding saga of the IPL, Lucknow Super Giants stand as the eager protagonist, fresh-faced and filled with aspiration. Chennai Super Kings, on the other hand, are the seasoned protagonist, a character etched in experience, led by the enigmatic Dhoni. When these two tales intertwine, it''s a meeting of beginnings and continuations, where youth meets wisdom in the cricketing narrative.','Wed','League'),
 (790055,'Punjab Kings','Mumbai Indians','Mohali','2023-05-03','PCA IS Bindra Stadium','960 - 11200','19:30:00','Punjab Kings and Mumbai Indians - two narratives of contrasting shades. Punjab, with its unpredictable brilliance, is a story of ups and downs. Mumbai, with its rich legacy, is a narrative of dominance and success. When these stories collide, it''s a tale of unpredictability versus established greatness, a plot with twists and turns.','Thu','League'),
 (822156,'Sunrisers Hyderabad','Kolkata Knight Riders','Hyderabad','2023-05-04','Rajiv Gandhi International Stadium','960 - 11200','19:30:00','In the grand theater of the IPL, the Sunrisers Hyderabad and the Kolkata Knight Riders take center stage. Hyderabad, with its formidable bowling prowess, embodies resilience. Kolkata Knight Riders, with their championship victories, symbolize charisma. When these narratives merge, it''s a duel of tactics and flair, a cricketing drama for the ages.','Thu','League'),
 (809880,'Rajasthan Royals','Gujarat Titans','Jaipur','2023-05-05','Sawai Mansingh Stadium','750 - 12900','19:30:00','In the grand arena of the Indian Premier League, Rajasthan Royals and Gujarat Titans are like two parallel rivers, each on its own unique journey. The Royals, carrying the weight of regal history, represent the essence of resilience in the face of adversity. Meanwhile, the Titans, hailing from a land of unwavering determination, emerge as a testament to the power of striving against the odds. When they converge, it''s more than a cricket match; it''s a reflection of the human spirit''s diverse expressions.','Fri','League'),
 (202911,'Chennai Super Kings','Mumbai Indians','Chennai','2023-05-06','M.A Chidambaram Stadium','990 - 10200','15:30:00','In the theatre of cricket, the Chennai Super Kings and Mumbai Indians are the seasoned actors, each performing their part with precision and grace. Chennai, led by the enigmatic Dhoni, personifies the art of patience and strategy, while Mumbai, with its storied success, embodies the ever-advancing rhythm of a bustling metropolis. When they face off, it''s not just a match; it''s a symphony of experience and ambition, a dance of tradition and innovation.','Sat','League'),
 (150122,'Delhi Capitals','Royal Challengers Bangalore','Delhi','2023-05-06','Arun Jaitley Stadium','810 - 11000','19:30:00','Delhi Capitals and Royal Challengers Bangalore, like two philosophers of the cricketing realm, engage in a battle of intellect and insight. Delhi, representing the nation''s capital, carries the weight of responsibility and strategy. Meanwhile, Bangalore, a perennial contender, exemplifies consistency and the pursuit of excellence. When these two minds collide, it''s not merely a game; it''s a discourse on the essence of competition and the quest for mastery.','Sat','League'),
 (343157,'Gujarat Titans','Lucknow Super Giants','Ahmedabad','2023-05-07','Narendra Modi Stadium','900 - 10600','15:30:00','Gujarat Titans and Lucknow Super Giants, the emerging stars of the IPL, enter the arena as tales in the making. Gujarat''s relentless spirit and Lucknow''s boundless ambition come together, creating a canvas of dreams and determination. This match is a chapter in the epic of cricket, where new stories are authored and fresh legends emerge.','Sun','League'),
 (277585,'Rajasthan Royals','Sunrisers Hyderabad','Jaipur','2023-05-07','Sawai Mansingh Stadium','950 - 14200','19:30:00','Rajasthan Royals and Sunrisers Hyderabad, two teams with unique character, engage in a battle of identity and purpose. Rajasthan''s regal spirit meets Hyderabad''s unwavering precision, crafting a narrative of elegance and determination. When they cross paths, it''s not just a cricket match; it''s a quest to define one''s essence in the grand tapestry of the IPL.','Sun','League'),
 (404988,'Kolkata Knight Riders','Punjab Kings','Kolkata ','2023-05-08','Eden Gardens Stadium','1200-10000','19:30:00','In the saga of the IPL, Kolkata Knight Riders and Punjab Kings emerge as storytellers, each with a distinctive plot to narrate. Kolkata, with its charismatic flair, takes on Punjab, known for its unpredictability and brilliance. When they meet, it''s a chapter of contrast and intrigue, a testimony to the diversity of cricketing tales.','Mon','League'),
 (568911,'Mumbai Indians','Royal Challengers Bangalore','Mumbai','2023-05-09','Wankhede Stadium','740 - 13400','19:30:00','In the arena of the Indian Premier League, Mumbai Indians and Royal Challengers Bangalore are like constellations in the night sky. Mumbai, with its star-studded lineup and a history of championship victories, represents the luminary champions. On the other hand, Royal Challengers Bangalore, the perennial contenders, shine with the light of consistency and determination. When they converge, it''s a celestial clash of talent and resolve.','Tue','League'),
 (489233,'Chennai Super Kings','Delhi Captials','Chennai','2023-05-10','M.A Chidambaram Stadium','650 - 14200','19:30:00','Chennai Super Kings, the masters of strategy and experience, engage in a battle of wits with Delhi Capitals, representing the nation''s capital and the pursuit of excellence. Chennai, with its tactical prowess, meets Delhi''s calculated approach. When these two minds collide, it''s not just a game; it''s a discourse on the essence of competition and the quest for mastery.','Wed','League'),
 (859387,'Kolkata Knight Riders','Rajasthan Royals','Kolkata ','2023-05-11','Eden Gardens Stadium','1200-10000','19:30:00','In the IPL''s grand narrative, Kolkata Knight Riders and Rajasthan Royals take their places as storytellers, each with a distinctive plot to narrate. Kolkata, with its charismatic flair, faces Rajasthan, known for its regal underdog spirit and a history of surprising triumphs. When they meet, it''s a chapter of contrast and intrigue, a testament to the diversity of cricketing tales.','Thu','League'),
 (164045,'Mumbai Indians','Gujarat Titans','Mumbai','2023-05-12','Wankhede Stadium','800 - 11500','19:30:00','In the grand theatre of the Indian Premier League, Mumbai Indians and Gujarat Titans stand as seasoned actors, each with a unique role to play. Mumbai, a city of dreams and IPL championships, takes the stage as a symbol of consistency. Gujarat Titans, new entrants with boundless ambition, enter with the energy of emerging stars. When they face off, it''s not just a match; it''s a performance of tradition and aspiration.','Fri','League'),
 (216130,'Sunrisers Hyderabad','Lucknow Super Giants','Hyderabad','2023-05-13','Rajiv Gandhi International Stadium','700 - 11300','15:30:00','Sunrisers Hyderabad, known for their formidable bowling prowess, cross paths with Lucknow Super Giants, the newest entrants to the IPL. It''s a duel between precision and ambition, where Sunrisers'' accuracy meets Lucknow''s vigor. This encounter is not just a cricket match; it''s a test of established technique against emerging enthusiasm.','Sat','League'),
 (156569,'Delhi Capitals','Punjab Kings','Delhi','2023-05-13','Arun Jaitley Stadium','800 - 12500','19:30:00','Delhi Capitals and Punjab Kings, two franchises with their unique narratives, engage in a contest of strategy and unpredictability. Delhi, representing the nation''s capital, carries the weight of responsibility, while Punjab Kings, known for their flair and unpredictability, bring an element of surprise. When these two worlds collide, it''s not just a game; it''s a clash of contrasting styles and cricketing philosophies.','Sat','League'),
 (471085,'Rajasthan Royals','Royal Challengers Bangalore','Jaipur','2023-05-14','Sawai Mansingh Stadium','670 - 11200','15:30:00','In the arena of the Indian Premier League, Rajasthan Royals and Royal Challengers Bangalore stand as two distinct narratives. Rajasthan, with its underdog spirit and history of remarkable triumphs, faces Royal Challengers Bangalore, a perennial favorite. When they meet, it''s a clash of the steadfast underdogs against the enduring contenders, a cricketing saga of determination versus consistency.','Sun','League'),
 (968970,'Chennai Super Kings','Kolkata Knight Riders','Chennai','2023-05-14','M.A Chidambaram Stadium','830 - 11000','19:30:00','Chennai Super Kings, the masters of strategy and experience, cross swords with the charismatic Kolkata Knight Riders, known for their flair and unpredictability. Chennai''s tactical brilliance meets Kolkata''s magnetic enthusiasm. When these two worlds collide, it''s not just a cricket match; it''s a discourse on the essence of competition and the quest for mastery.','Sun','League'),
 (522508,'Gujarat Titans','Sunrisers Hyderabad','Ahmedabad','2023-05-15','Narendra Modi Stadium','750 - 14600','19:30:00','In the grand tapestry of the IPL, the newly emerged Gujarat Titans face off against the established precision of Sunrisers Hyderabad. Gujarat, filled with ambition and energy, encounters Sunrisers, known for their formidable bowling prowess. This match is a testament to the spirit of the IPL, where new dreams challenge established technique.','Mon','League'),
 (132603,'Lucknow Super Giants','Mumbai Indians','Lucknow','2023-05-16','Ekana Cricket Stadium','790 - 13800','19:30:00','Lucknow Super Giants, the IPL''s newcomers, take on the mighty Mumbai Indians, a team with a history of championship victories. It''s a clash of fresh ambition versus seasoned experience, where youth and vigor meet established greatness.','Tue','League'),
 (348232,'Punjab Kings','Delhi Captials','Dharamshala','2023-05-17','HPCA Stadium','790 - 11500','19:30:00','Punjab Kings and Delhi Capitals, two franchises with unique narratives, engage in a contest of strategy and flair. Delhi, representing the nation''s capital, carries the weight of responsibility and consistency. Meanwhile, Punjab Kings, known for their unpredictable brilliance, bring an element of surprise. When these two worlds collide, it''s not just a game; it''s a clash of contrasting styles and cricketing philosophies.','Wed','League'),
 (980666,'Sunrisers Hyderabad','Royal Challengers Bangalore','Hyderabad','2023-05-18','Rajiv Gandhi International Stadium','810 - 10400','19:30:00','Sunrisers Hyderabad, known for their formidable bowling prowess, face the enduring contenders, Royal Challengers Bangalore. It''s a clash of precision and consistency, where Sunrisers'' accuracy meets Bangalore''s enduring spirit. This encounter is not just a cricket match; it''s a test of technique against unwavering determination.','Thu','League'),
 (101175,'Punjab Kings','Rajasthan Royals','Dharamshala','2023-05-19','HPCA Stadium','970 - 11600','19:30:00','Punjab Kings and Rajasthan Royals, two franchises with their unique narratives, engage in a contest of strategy and underdog spirit. Punjab, known for their unpredictable brilliance, faces Rajasthan, a team with a history of remarkable triumphs. When these two worlds collide, it''s not just a game; it''s a clash of contrasting styles and cricketing philosophies.','Fri','League'),
 (720854,'Delhi Capitals','Chennai Super Kings','Delhi','2023-05-20','Arun Jaitley Stadium','860 - 10600','15:30:00','Delhi Capitals, representing the nation''s capital, meet the masters of strategy and experience, Chennai Super Kings. It''s a discourse on the essence of competition, responsibility, and pursuit of mastery. When these two worlds collide, it''s not just a cricket match; it''s a contest of contrasting philosophies and styles.','Sat','League'),
 (894532,'Kolkata Knight Riders','Lucknow Super Giants','Kolkata ','2023-05-20','Eden Gardens Stadium','1200-10000','19:30:00','Kolkata Knight Riders, known for their charismatic flair, face Lucknow Super Giants, the IPL''s newcomers brimming with ambition. It''s a meeting of experience and enthusiasm, where the seasoned showmanship of Kolkata meets the vigor of Lucknow.','Sat','League'),
 (136082,'Mumbai Indians','Sunrisers Hyderabad','Mumbai','2023-05-21','Wankhede Stadium','790 - 12100','15:30:00','Mumbai Indians, a team with a history of championship victories, take on Sunrisers Hyderabad, known for their formidable bowling prowess. When they clash, it''s a showdown of dominance and precision, a cricketing spectacle of established greatness versus technical expertise.','Sun','League'),
 (910703,'Royal Challengers Bangalore','Gujarat Titans','Bengaluru','2023-05-21','M. Chinnaswamy Stadium','720 - 13100','19:30:00','Royal Challengers Bangalore, the perennial contenders, engage in a battle of consistency with the emerging stars of the Gujarat Titans. Bangalore''s enduring spirit meets Gujarat''s boundless ambition. When they meet, it''s a clash of established favorites and rising hopes in the IPL.','Sun','League'),
 (514467,'Team 1','Team 2','Chennai','2023-05-23','M.A Chidambaram Stadium','780 - 14400','15:30:00','In the heart-pounding qualifier, the stakes are high, and only one team will claim the throne to challenge destiny in the final showdown.','Tue','Qualifier 1'),
 (796626,'Team 3','Team 4','Chennai','2023-05-24','M.A Chidambaram Stadium','760 - 14800','15:30:00','In the fierce eliminator, survival is the only option as two teams clash with their tournament hopes hanging by a thread.','Wed','Eliminator'),
 (112927,'Loser of Qualifier 1','Winner of Eliminator','Ahmedabad','2023-05-26','Narendra Modi Stadium','740 - 13300','15:30:00','In this IPL qualifier, the battle of champions unfolds as two cricketing titans vie for a ticket to the grand finale.','Fri','Qualifier 2'),
 (640182,'Winner of Qualifier 1','Winner of Qualifier 2','Ahmedabad','2023-05-28','Narendra Modi Stadium','930 - 14200','15:30:00','In the IPL finals, destiny beckons as two elite teams go head to head, chasing cricketing immortality and the coveted championship.','Sun','Finals'),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','',''),
 ('','','','','','','','','','','');
COMMIT;
